//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TESTPROJSCAN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public long Id { get; set; }
        public string EmployeeNo { get; set; }
        public string NicNo { get; set; }
        public string FullName { get; set; }
        public string NameWithInitials { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<int> EmployeeTypeId { get; set; }
        public Nullable<int> GenderId { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> DesignationId { get; set; }
        public Nullable<int> SalaryPackageId { get; set; }
        public Nullable<System.DateTime> JoinedDate { get; set; }
        public string PhoneNo { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
    }
}
