//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TESTPROJSCAN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPermissionHistory
    {
        public long Id { get; set; }
        public Nullable<int> UserRoleId { get; set; }
        public Nullable<int> InterMenuId { get; set; }
        public Nullable<int> PermissionTypeId { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedTime { get; set; }
    
        public virtual UserPermissionType UserPermissionType { get; set; }
        public virtual UserRole UserRole { get; set; }
        public virtual User User { get; set; }
    }
}
